# Generated by Django 5.0.1 on 2024-02-17 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='blogapp.author'),
            preserve_default='True',
        ),
    ]
