# Generated by Django 5.0.1 on 2024-02-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='blogapp.post'),
            preserve_default='True',
        ),
    ]
