# Generated by Django 5.0.1 on 2024-02-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_blog_banner_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_banner',
            field=models.ImageField(upload_to='blog_banners/'),
        ),
    ]
